### ISSUE TITLE
Control notifications manually.

### ISSUE THREAD

**Issue by cainrus** [pushy-me/pushy-cordova#10]
It's impossible to detect pending(in top menu) push notifications, count them or read their ids.
It's impossible to remove notifications from top menu/bar with javascript API.

**Comment by pushy** [comment]
Hi @cainrus,
This functionality is unfortunately out of the scope of our Cordova SDK. If you wish to manage the your app's existing notifications, you can either write native code to do so (as the Cordova JavaScript APIs do not expose this functionality), or use a plugin such as `cordova-plugin-local-notifications`:
https://github.com/katzer/cordova-plugin-local-notifications/wiki/06.-Clear
