### ISSUE TITLE
Pushy.setNotificationListener bug

### ISSUE THREAD

**Issue by cainrus** [pushy-me/pushy-cordova#11]
Hello.

Pushy.setNotificationListener has strange behaviour:

**Scenario 1**

1) cordova ios application is not running (not in a background)
2) I send notification via pushy.me dashboard
3) notification appears in a top of device screen
4) tap on notification
5) app is starting
6) notification callback is not called.

**Scenario 2**
1) cordova android application is in a background
2) I send notification via pushy.me dashboard
3) notification does appears in a top of device screen
4) callback handler is called (app is still in a background)

**Comment by pushy-me** [comment]
Hi @cainrus,
Thanks so much for the report. We have fixed the issue described in Scenario 1 in the newest version of our Cordova SDK `1.0.23`.

Please update by running this command:

```
cordova plugin add pushy-cordova@1.0.23
```

**Comment by pushy** [comment]
Hi @cainrus,
Thanks so much for the report. We have fixed the issue described in Scenario 1 in the newest version of our Cordova SDK `1.0.24`.

Please update by running this command:

```
cordova plugin add pushy-cordova@1.0.24
```
Then, rebuild your project and check if the issue is resolved.
