### ISSUE TITLE
Unable to build cordova ios plugin: getNotificationHandler is not defined

### ISSUE THREAD

**Issue by cainrus** [pushy-me/pushy-cordova#12]
https://github.com/pushy-me/pushy-cordova/blob/f8f16e9d2c3668a4675033fe22506f7757b712af/src/ios/PushyPlugin.swift#L111

**Comment by pushy** [comment]
Hi @cainrus,
Apologies, we have just fixed this in `1.0.25`:

```
cordova plugin add pushy-cordova@1.0.25
```
