### ISSUE TITLE
Notification Tap event for iOS

### ISSUE THREAD

**Issue by alvarofelipe12** [pushy-me/pushy-cordova#16]
Hello.

I saw a closed [issue](https://github.com/pushy-me/pushy-cordova/issues/9) but it suggest a not longer maintained plugin for Android/iOS...

It will be great if pushy will be capable of do this things without modify the plugin or add new plugins.

Thanks for your time.

**Comment by pushy** [comment]
**Update:** Please see [this answer](https://github.com/pushy-me/pushy-cordova/issues/16#issuecomment-557316805) first.

@alvarofelipe12 You can achieve notification tapped events on iOS by checking whether your app is in the foreground or background when your notification listener callback is called.

All notifications that invoke your `Pushy.setNotificationListener()` while your app is in background are notification tap events.

```
var isBackground = true;

function onDeviceReady() {
    document.addEventListener("pause", onPause, false);
    document.addEventListener("resume", onResume, false);
    // Add similar listeners for other events
}

function onPause() {
   isBackground = true;
}

function onResume() {
    isBackground = false;
}

// Listen for push notifications
Pushy.setNotificationListener(function (data) {
    // Notification tapped in background?
    if (isBackground) {
        // Display an alert with the "message" payload value
        alert(data.message);
    }
});
```

**Comment by pushy** [comment]
Hi @alvarofelipe12 and @EddyVerbruggen,
Great news! We have just finished integrating this functionality into the SDK.

Call the `Pushy.setNotificationClickListener((data) => {})` method from your application to listen for when the user clicks your notifications:

```
// Listen for push notifications clicked
Pushy.setNotificationClickListener(function (data) {
    // Print notification payload data
    console.log('Clicked notification: ' + JSON.stringify(data));

    // Display an alert with the "message" payload value
    alert('Clicked notification: ' + data.message);

    // Navigate the user to another page or 
    // execute other logic on notification click
});
```

This method is supported on both Android and iOS. Inside this method, you can then check the notification payload which was clicked and direct the user to the relevant page in your Cordova app or execute other custom logic on notification click.

To be able to access this method, please update the Pushy Cordova SDK in your app by running the following commands in the root of your Cordova project (these will delete any modifications you have made to `pushy-push-receiver`):

```
cordova plugin remove pushy-cordova-receiver
cordova plugin remove pushy-cordova

cordova plugin add pushy-cordova@1.0.29
cordova plugin add ./plugins/pushy-cordova/receiver/
```

Please let me know if you face any issues.
