### ISSUE TITLE
use pushy.me and phonegap-plugin-push together

### ISSUE THREAD

**Issue by YaroslavG** [pushy-me/pushy-cordova#17]
hi guys, 
Is it possible to use this plugin together with [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-pushl) in one ionic project ?

**Comment by pushy** [comment]
Hi @YaroslavG,
I'd be glad to help.

On Android, yes, you may use our Ionic/Cordova plugin simultaneously with `phonegap-plugin-push` which relies on FCM, these plugins do not intersect. 

However, on iOS, we register for notifications using the Apple Push Notification Service, just like `phonegap-plugin-push`, and both plugins attempt to hijack the APNs methods in the `AppDelegate` class. Using these plugins together on iOS is therefore not supported.

We recommend not invoking the `phonegap-plugin-push` plugin for iOS and using it just for Android to deliver notifications via FCM and Pushy simultaneously.
