### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by martindederer** [pushy-me/pushy-cordova#2]
Do you have any plans to support iOS as a target platform? The usefulness of this plugin is rather limited for cross platform development with cordova as long as only the android platform is supported.

**Comment by pushy** [comment]
Hi @martindederer,
Absolutely! 

We understand your concern. iOS support for our Cordova plugin is expected within several weeks. We will be sure to let you know once it's ready. 👍

**Comment by martindederer** [comment]
Great! I am looking forward to it.

**Comment by davidst2017** [comment]
Hi guys, any news concerning the iOS support?

**Comment by pushy** [comment]
Hi @davidst2017,
Unfortunately no, Cordova iOS support for our SDK not been completed yet. ETA is a few weeks from now. 

We will update this issue when more information becomes available.

**Comment by NDallaRiva** [comment]
Hi guys, any news concerning the iOS support?

**Comment by pushy** [comment]
Hi @NDallaRiva,
Unfortunately no, Cordova iOS support for our SDK not been completed yet. ETA is a few weeks from now.

We will update this issue when more information becomes available.

**Comment by pushy** [comment]
Hi @martindederer, @davidst2017, and @NDallaRiva,
Great news! 

We have officially released support and documentation for Cordova iOS:
https://pushy.me/docs/additional-platforms/cordova

Thank you for your patience.

**Comment by martindederer** [comment]
Thanks. :)
