### ISSUE TITLE
ios build failed with this prompt

### ISSUE THREAD

**Issue by crapthings** [pushy-me/pushy-cordova#21]
we're using meteor 1.8.1 currently for our app
the cordova shipped with meteor is kinda old.

but i can click "fix" to bypass the error, but don't know if it causes #20 

![image](https://user-images.githubusercontent.com/1147704/71512316-8d784700-28d0-11ea-97ab-db97d6fb6ecb.png)

**Comment by pushy** [comment]
Hi @crapthings,
It seems that your project is configured to compile with a newer version of Swift than the one that comes preconfigured in a fresh Cordova project.

You can go ahead and apply the suggested Xcode fix without any adverse affects. It is not related to #20. Please see our response for that issue 👍
