### ISSUE TITLE
setNotificationListener is not working for ios

### ISSUE THREAD

**Issue by CrackerakiUA** [pushy-me/pushy-cordova#22]
I followed guide in https://pushy.me/docs/additional-platforms/cordova and everything is working for android, in ios register device is also working but `setNotificationListener` is never called. I also tested `setNotificationClickListener` which is also not called when we tap on the notification

**Comment by pushy** [comment]
Hi @CrackerakiUA,
We'd be glad to assist.

1) Where are you calling `Pushy.setNotificationListener((data) => {})`?

We recommend placing this method invocation in your `www/js/index.js` file's `onDeviceReady()` method.

Please move it there and see if it resolves the issue.

2) Does your Cordova app use any other push plugin such as `phonegap-plugin-push` or OneSignal? These may collide with the Pushy SDK.

**Comment by CrackerakiUA** [comment]
1. I will try it there for testing, I am using it inside of device ready. As I mentioned `Pushy.register(function (err, deviceToken) {});` is giving me the deviceToken normally and app is receiving pushes.
2. No, Pushy is the only push plugin I am using on the app.

**Comment by pushy** [comment]
Hi @CrackerakiUA,
Please update on whether moving the method to `onDeviceReady()` resolves the issue.

**Comment by CrackerakiUA** [comment]
This issue was due to I was using xcode 10 and plugin was not working. After build  on latest xcode everything was working smoothly.
