### ISSUE TITLE
[Android] How to know when the app is opened from a notification

### ISSUE THREAD

**Issue by CodeWithOz** [pushy-me/pushy-cordova#27]
How can I determine if the app was opened from a notification on Android?

**Comment by pushy** [comment]
Hi @CodeWithOz,
You may call the `Pushy.setNotificationClickListener((data) => {})` method from your application to listen for when the user taps your notifications.

To check whether the app was opened from the notification click, we'd recommend storing the timestamp of when the `onDeviceReady()` callback was executed, and checking if less than 3 seconds passed from when the notification click callback was invoked.

Add this code to your `www/js/index.js` file's `onDeviceReady()` method to store the app launch timestamp:

```
this.appLaunch = new Date().getTime();
```

Then, use the following notification click listener code:

```
// Listen for notification click
Pushy.setNotificationClickListener(function (data) {
    // Print notification payload data
    console.log('Notification click: ' + JSON.stringify(data));

    // Check if app was opened recently (in past 3 seconds)
    if (this.appLaunch && this.appLaunch > new Date().getTime() - 3000) {
        // App was opened from notification

        // Display an alert with the "message" payload value
        alert('Notification click: ' + data.message);

        // Navigate the user to another page or 
        // execute other logic on notification click
    }
});
```

**Comment by CodeWithOz** [comment]
Thank you. Just curious, why is the threshold set to 3 seconds? Why not 5s, or even 1s?

**Comment by pushy** [comment]
Hi @CodeWithOz,
Just to account for any delays in between your app being launched and the notification click listener being fired. `3s` or `5s` should be more than enough.
