### ISSUE TITLE
iOS Push notifications not working in Build created from Xcode 12 and Apple Macbook M1

### ISSUE THREAD

**Issue by siddharthhudda** [pushy-me/pushy-cordova#28]
Use case: iOS Push notifications not working in Build created from Xcode 12 and Apple Macbook M1. There is no dialogue pops up at app launch for notification permissions in iOS devices.

Environment:
1. Apple Macbook Pro (M1)
2. Xcode 12
3. pushy-cordova plugin versions (1.0.39, 1.0.38) 
4. iOS 14

Note: Please look into it on urgent basis. We are using pushy and cannot release our apps to Apple app store without notifications. Many of the crucial features are dependent on notifications.

**Comment by pushy** [comment]
Hi @siddharthhudda,
Did the dialog ever display on that device while running your app? Was it declined by accident?

As per the [Apple docs](https://developer.apple.com/library/archive/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42), it may be necessary to reset the push notification dialog:

> The first time a push-enabled app registers for push notifications, iOS asks the user if they wish to receive notifications for that app. Once the user has responded to this alert it is not presented again unless the device is restored or the app has been uninstalled for at least a day. If you want to simulate a first-time run of your app, you can leave the app uninstalled for a day. You can achieve the latter without actually waiting a day by following these steps:

1. Delete your app from the device.
2. Turn the device off completely and turn it back on.
3. Go to Settings > General > Date & Time and set the date ahead a day or more.
4. Turn the device off completely again and turn it back on.

Please let us know if this resolves the issue.

**Comment by siddharthhudda** [comment]
Yes. It helped me a lot. Now notifications are working. 

Thanks
