### ISSUE TITLE
Is there any example or tutorial for angular ionic + capacitor + pushy?

### ISSUE THREAD

**Issue by ramseyfeng** [pushy-me/pushy-cordova#29]
I try to set up by following the guide: 
[https://pushy.me/docs/additional-platforms/capacitor](https://pushy.me/docs/additional-platforms/capacitor)

On step: Modify Index File

Add the following code to your www/js/capacitor-welcome.js file
 `Pushy.listen();`

I don't where to put above code, could it be more clear?
Can we add this listener in Angular code? or we should put it in capacitor code?

**Comment by pushy** [comment]
Hi @ramseyfeng,
Thanks for your inquiry.

Our docs state that this line of code should be placed in your `connectedCallback()` method inside an `HTMLElement` class defined in your Capacitor project.

If you don't have this method defined yet, you can define it in `HTMLElement` as was done here:
https://github.com/ionic-team/create-capacitor-app/blob/main/assets/app-template/www/js/capacitor-welcome.js#L89

Please let us know if you have any further questions.

**Comment by ramseyfeng** [comment]
Thanks for reply!
Actually my question is regarding ionic + capacitor, and later i found the ionic doc is more accurate, so we don't need to modify capacitor-welcome.js if we are using ionic + capacitor.

**Comment by pushy** [comment]
Hi @ramseyfeng,
Indeed our answer is also regarding Ionic + Capacitor. Are we correct to assume that you have found the solution to your inquiry in the Ionic docs, or do you still require assistance?

**Comment by ramseyfeng** [comment]
Hi @pushy-me ,

Yes, we found the solution for it.
