### ISSUE TITLE
Compliance with Android 8

### ISSUE THREAD

**Issue by NDallaRiva** [pushy-me/pushy-cordova#3]
If I run this version on an Android 8 the listener receives the data but no notification is shown, even after disabling all the battery optimizations for the app.

As you could find here ( https://developer.android.com/guide/topics/ui/notifiers/notifications.html )
"If you target Android 8.0 (API level 26) and post a notification without specifying a valid notifications channel, the notification fails to post and the system logs an error".

I changed something in the PushReceiver, to make it fit Android 8.
[PushReceiver.java.zip](https://github.com/pushy-me/pushy-cordova/files/1726740/PushReceiver.java.zip)

Clearly this version works just on Android 8 since we have not Notification Channels in previous versions, so a management mechanism has to be add in order to be compliant even to older versions.

**Comment by pushy** [comment]
Hi @NDallaRiva,
Thanks so much for your help with this. 

We will be modifying [PushReceiver.java](https://github.com/pushy-me/pushy-cordova/blob/a0add1201d73e1fe9c1b1434f17e42a4ab892255/receiver/src/android/PushReceiver.java) and adding notification channels to resolve this issue, and will let you know once that's ready.

**Comment by pushy** [comment]
Hi @NDallaRiva,
The newest version of the Pushy SDK for Cordova apps now supports Android O notification channels.

Thanks for your help! 👍
