### ISSUE TITLE
Error after installing another plugin

### ISSUE THREAD

**Issue by CodeWithOz** [pushy-me/pushy-cordova#32]
I get the following error after installing the [openwith plugin](https://github.com/j3k0/cordova-plugin-openwith) plugin:
```
/Users/vagrant/git/platforms/android/app/src/main/AndroidManifest.xml:105:9-109:19 Error:
	Element service#me.pushy.sdk.services.PushyFirebaseService at AndroidManifest.xml:105:9-109:19 duplicated with element declared at AndroidManifest.xml:100:9-104:19
/Users/vagrant/git/platforms/android/app/src/main/AndroidManifest.xml:110:9-114:19 Warning:
	Element service#me.pushy.sdk.services.PushyFirebaseService at AndroidManifest.xml:110:9-114:19 duplicated with element declared at AndroidManifest.xml:105:9-109:19
/Users/vagrant/git/platforms/android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting
```

I tried to compare the `plugin.xml` of both plugins but didn't find any duplicated values. Any ideas as to what the problem may be?

**Comment by pushy** [comment]
Hi @CodeWithOz,
We'd be glad to assist.

Most likely, removing and re-creating the Android platform directory will resolve this issue:

```
cordova platform remove android
cordova platform add android
```

This will wipe any modifications you made to the Android native project.

**Comment by CodeWithOz** [comment]
Thanks but this error is happening on a CI system that always installs the platforms fresh with each build. Given that the openwith plugin is open source, could you please review it to identify what is getting duplicated? I tried to do that in the `plugin.xml` files but didn't find anything, but you'll be more familiar with what exactly the pushy plugin is doing so you may catch something that I missed.

**Comment by CodeWithOz** [comment]
The error references the config needed for Pushy's FCM fallback, specifically this bit:
```
            <service
                android:name="me.pushy.sdk.services.PushyFirebaseService"
                android:exported="false"
                android:stopWithTask="false">
                <intent-filter>
                    <action android:name="com.google.firebase.MESSAGING_EVENT" />
                </intent-filter>
            </service>
```

In the `plugin.xml` of the openwith plugin, the only code I found that looks similar is this:
```
        <config-file target="AndroidManifest.xml" parent="/manifest/application/activity">
            <intent-filter>
                <!-- category android:name="android.intent.category.BROWSABLE" / -->
                <!-- See https://developer.android.com/guide/topics/manifest/data-element.html -->
                <data android:mimeType="$ANDROID_MIME_TYPE" />
                <action android:name="android.intent.action.SEND" />
                $ANDROID_EXTRA_ACTIONS
                <!-- action android:name="android.intent.action.VIEW" / -->
                <!-- action android:name="android.intent.action.SEND_MULTIPLE" / -->
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </config-file>
```
But the intent-filters are clearly different.

---
However it seems the FCM fallback docs were updated recently because I now see `android:priority="100"` in the intent-filter, and a notice that Cordova-based apps should skip this step entirely. I'll comment it out and repeat the build to see if that helps.

**Comment by pushy** [comment]
Hi @CodeWithOz,
If you aren't using the FCM Fallback feature, a valid workaround is to comment out the `<service>` declaration entirely to see if it resolves the issue.

**Comment by CodeWithOz** [comment]
@pushy-me yes I tried that and it worked, but I am using the FCM fallback feature. What are my options then?

**Comment by pushy** [comment]
Hi @CodeWithOz,
Please post the contents of your `/Users/vagrant/git/platforms/android/app/src/main/AndroidManifest.xml` file when the build error occurs so we can take a look at what the Cordova build process is complaining about.

**Comment by CodeWithOz** [comment]
Cordova dynamically generates the file during the build step, I don't have access to it beforehand. That's why I suggested looking over the other plugin's code to see if there are any duplicated configurations.

**Comment by pushy** [comment]
@CodeWithOz Sure, we've looked at the other plugin's [`plugin.xml` file](https://github.com/j3k0/cordova-plugin-openwith/blob/master/plugin.xml) and there doesn't seem to be any conflict. The only change they are making to the `AndroidManifest.xml` is the following addition under the main `<activity>` tag:

```
<intent-filter>
                <!-- category android:name="android.intent.category.BROWSABLE" / -->
                <!-- See https://developer.android.com/guide/topics/manifest/data-element.html -->
                <data android:mimeType="$ANDROID_MIME_TYPE" />
                <action android:name="android.intent.action.SEND" />
                $ANDROID_EXTRA_ACTIONS
                <!-- action android:name="android.intent.action.VIEW" / -->
                <!-- action android:name="android.intent.action.SEND_MULTIPLE" / -->
                <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

The Pushy Cordova SDK does not make any changes to the `<activity>` tag. Therefore, we believe something else it at play (possibly the Pushy SDK `<service>` declaration is being added twice to the build file by accident). That's why it would be really helpful to check lines #105 and #110 of that file.

Can you please try building, and after the error represents itself, share the contents of `/Users/vagrant/git/platforms/android/app/src/main/AndroidManifest.xml` here?

**Comment by CodeWithOz** [comment]
Okay thank you :+1: . I do the builds on a CI system rather than locally so I normally don't have access to the file. I'll try to get it and post here.

**Comment by CodeWithOz** [comment]
Oddly the build worked with the FCM fallback after i reactivated it to try to get the error. If the problem comes up again I'll try to get more info and re-open this. Thanks!
