### ISSUE TITLE
Unregister device token on iOS

### ISSUE THREAD

**Issue by qpre** [pushy-me/pushy-cordova#33]
Hello,

How would you unregister a device on iOS ?

Thanks,

**Comment by pushy** [comment]
Hi @qpre,
We'd be glad to clarify.

To stop receiving notifications on an iOS device, the recommended implementation approach is to make a web request from your iOS app to your backend server, to clear the saved Pushy device token for that user from your backend database. That way, it won't be sent to our Send Notifications API any longer.

When you're ready to receive notifications again on that device, simply have the iOS app send the Pushy device token to your backend for renewed storage, so it gets sent to the Send Notifications API again.

Please let us know if you have any questions.
