### ISSUE TITLE
iOS push notification title

### ISSUE THREAD

**Issue by nesha14586** [pushy-me/pushy-cordova#35]
We are using Pushy for delivering push notifications to our app. Problem is, title of push notifications is not showing on iOS.

On Android it works well after modifying PushReceiver.java. On iOS we don't know how to achieve it.

When contacting Pushy support, they first said "Setting a custom "title" only works on iOS 8.2+." and after couple more emails they said "If setting the title via "notification.title" isn't working for your iOS device, then it isn't possible otherwise. Apple doesn't directly mention that it works for iPhones, only for Apple Watch" and referenced this from Apple developer docs: The title of the notification. Apple Watch displays this string in the short look notification interface. Specify a string that’s quickly understood by the user.

Almost every app on my iPhone has notifications with a title and I bet lots of apps use Pushy too.

Is there a way to add title for iOS notifications?

Dependencies used:
"pushy-cordova": "^1.0.45",
"pushy-cordova-receiver": "file:node_modules/pushy-cordova/receiver",

**Comment by pushy** [comment]
Hi @nesha14586,
Thanks for reaching out. We'd be glad to assist.

We can confirm that setting the `notification.title` parameter of the [Send Notifications API](https://pushy.me/docs/api/send-notifications) indeed results in a title being displayed on iOS 8.2+ devices:

```
{
    "to": "a6345d0278adc55d3474f5",
    "data": {
        "message": "Hello World!"
    },
    "notification": {
        "body": "Hello World \u270c",
        "title": "Custom Title", <-------------------
        "sound": "ping.aiff"
    }
}
```

1) What version of iOS is your device running?

2) What is your app's configured **iOS Deployment Target** in the Xcode project editor's **Build Settings** tab? Please ensure it is set to **iOS 8.0** or higher.

3) It might be an issue with the request body you are sending to the Send Notifications API. Please use [this page](https://pushy.me/docs/api/send-notifications#try) to send your device a test notification with a title, by selecting your app from the dropdown, populating the `to` parameter with your test device's Pushy device token, and clicking **Show optional params** to reveal the `notification.title` field, for which you may populate it with `"Test"`.

**Comment by nesha14586** [comment]
Hi @pushy-me ,

Seems that we found the problem. I was convinced that backend guys were sending the correct notification object. After a few changes, it's now working.

Thanks for your reply! You can close this issue.

While we're here. One of our managers wrote to your support some time ago asking if the FCM fallback notifications are possible with ionic or is it just for the native implementations. I don't think we got an answer. Would appreciate if you can answer to him directly or here. Thanks!

**Comment by pushy** [comment]
Hi @nesha14586,
Glad to hear that!

As per your inquiry, FCM fallback is indeed **supported** on hybrid environments such as Ionic. Please follow the instructions [in our docs](https://pushy.me/docs/resources/fcm-fallback-delivery) to get started.
