### ISSUE TITLE
Android Push notification does not work when app is closed

### ISSUE THREAD

**Issue by husainmusa** [pushy-me/pushy-cordova#38]
It works fine when it's in background, but doesn't work when I simply close the app.i have applied " Battery optimization -> All Apps -> Find "YourAppName" -> Set to "Don't optimize". But it's not working

**Comment by pushy** [comment]
Hi @husainmusa,
We'd be glad to assist.

Are you running your app from Android Studio? When you run your app from within Android Studio, and you later terminate it by swiping it away from the recent apps, it will no longer receive notifications until reopened.
 
However, if you start your app directly from within the App Launcher on the device, and swipe it away, it will continue to receive notifications even after being swept away by the user.

This bug only surfaces when running your app from within Android Studio, and will not affect your end users' experience.

If you're still facing this issue after running your app from the launcher, if you could please provide the following information about a device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by husainmusa** [comment]
thank you for your reply..
Here i am using ionic 5 , Here is detail as you said..
Device manufacturer - ASUS
Device model name - ASUS X00RD
Android OS version : 8.0.0

**Comment by pushy** [comment]
Hi @husainmusa,
Please confirm you are **not** running your app from Android Studio. When you run your app from within Android Studio, and you later terminate it by swiping it away from the recent apps, it will no longer receive notifications until reopened.

Furthermore, to ensure your users on Asus devices will be able to receive notifications in background / app closed / Doze mode, please consider implementing [FCM high-priority fallback delivery](https://pushy.me/docs/resources/fcm-fallback-delivery), which makes it possible for devices to receive notifications in real time during Doze mode. Pushy will attempt to deliver your notifications through [MQTT](https://pushy.me/support#what-is-mqtt) and [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/)'s high priority channel simultaneously, effectively bursting through Doze mode and other third-party manufacturer power saving optimizations.

**Comment by husainmusa** [comment]
hi @pushy .. no i am not using Android Studio.. also i don't want touse FCM .
Also i have tried with 
Device manufacturer - NOKIA C01 plus
Device model name - TA-1396
Android OS version : 11
I am  receiving all notification 
Please help me

**Comment by pushy** [comment]
Let's continue discussions in #39.
