### ISSUE TITLE
Problem with iOS support

### ISSUE THREAD

**Issue by EnricoGiordano1992** [pushy-me/pushy-cordova#4]
Hi, I have tried the new iOS support without success. My code works on Android, but not on iOS. 
For iOS, I've enabled via Xcode the Push notification and Background mode for notification. Do I set anything else? How can I find the problem? Is there a verbose mode for a test?

**Comment by pushy** [comment]
Hi @EnricoGiordano1992,
Please reach out to us at support@pushy.me so we can debug this together more efficiently and without disclosing any sensitive information.
