### ISSUE TITLE
Pure Capacitor/Ionic app

### ISSUE THREAD

**Issue by jammin197** [pushy-me/pushy-cordova#40]
Hello, please when I am using cordova plugin, should I follow also Android docs?
This one:
https://pushy.me/docs/android/modify-androidmanifest

permissions, services, receivers in Android Manifest in case of Capaciotr/Ionic app using "pushy-cordova" npm (capacitor) plugin

**Comment by pushy** [comment]
Hi @jammin197,
Thanks for reaching out. We'd be glad to assist.

We offer platform-specific integration guides for Cordova, Capacitor and Ionic:
[ Ionic](https://pushy.me/docs/additional-platforms/ionic)
[ Cordova](https://pushy.me/docs/additional-platforms/cordova)
[ Capacitor](https://pushy.me/docs/additional-platforms/capacitor)

Please let us know if there's anything else we can help with.

**Comment by jammin197** [comment]
You did not answer my question... 
If I have an Ionic/Capacitor app. Should I modify AndroidManifest.xml? Should I put there permissions which are mentioned in native Android documentation?
`  
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

**Comment by pushy** [comment]
Hi @jammin197,
Please do **not** directly modify your `AndroidManifest.xml`. When you install the `pushy-cordova` plugin, it will automatically modify your `AndroidManifest.xml` as needed.

Please let us know if there's anything else we can help with.
