### ISSUE TITLE
IOS Mobile Network issue

### ISSUE THREAD

**Issue by intellectsatheeshkumar** [pushy-me/pushy-cordova#42]
Error(“Internet connection error: APNs server *-[courier.push.apple.com](http://courier.push.apple.com/) is unreachable on port 5233 due to lack of internet connection or restrictive firewall: query failed”, “NETWORK_FIREWALL_ERROR”)

**Comment by pushy** [comment]
Hi @intellectsatheeshkumar,
Thanks for reaching out. We'd be glad to assist.

We've just released version `1.0.56` of the Pushy Cordova SDK which makes it possible to disable the APNs connectivity check, in case it is incorrectly failing.

To be able to access this method, please update the Pushy Cordova SDK in your app by running the following commands in the root of your Cordova project (these will delete any modifications you have made to `pushy-cordova-receiver`):

```
cordova plugin remove pushy-cordova-receiver
cordova plugin remove pushy-cordova

cordova plugin add pushy-cordova@1.0.56
cordova plugin add ./plugins/pushy-cordova/receiver/
```

Then, open your `www/js/index.js file` and find:

```
Pushy.listen();
```

Add below:

```
// Disable APNs connectivity check
pushy.toggleAPNsConnectivityCheck(false);
```

Please let us know if there's anything else we can help with.
