### ISSUE TITLE
FGService is killed upon APP exit

### ISSUE THREAD

**Issue by thetongyi** [pushy-me/pushy-cordova#43]
Hello everyone,

I have managed to update the pushy/cordova plugin to be able to support a FGService that should serve notifications, even when the APP has been closed.

To do this, I updated the JAVA files to target version 113 of the SDK.

Changes:

***************

Plugin.xml:
<framework src="me.pushy:sdk:1.0.113" />

Pushy.js:
    {
        name: 'toggleForegroundService',
        noError: true,
        noCallback: true,
        platforms: ['android']
    },

***************

Plugin.xml

<string name="pushy_foreground_service_title">Pushy</string>
<string name="pushy_foreground_service_connected">Connected to the notification service</string>
<string name="pushy_foreground_service_connecting">Connecting...</string>
<string name="pushy_foreground_service_disconnected">Not connected to the notification service</string>

***************

PushyPlugin.java:
                if (action.equals("toggleForegroundService")) {
                    toggleForegroundService(args, callbackContext);
                }

&

        private void toggleForegroundService(JSONArray args, CallbackContext callback) {
        try {
            // Enable or disable  toggleForegroundService support
            Pushy.toggleForegroundService(args.getBoolean(0), cordova.getActivity());

            // Resolve the callback with success
            callback.success();
        }
        catch (Exception exc) {
            // Reject the callback with the exception
            callback.error(exc.getMessage());
        }
    }

***************

All works as expected, however the FGService is killed once the APP is closed.  The status bar for the FGService shows up, and shows 'Connected' etc. 

I would expect this service to stay alive / or getting restarted.  What am I missing?

I have added: 

<service android:name="me.pushy.sdk.services.PushySocketService" android:foregroundServiceType="remoteMessaging" android:stopWithTask="false"  />

and 

<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_REMOTE_MESSAGING" />

...to the "plugin.xml", but my Android phone still kills the process when exiting the APP.

I am using a Huawei Pura Ultra 70, and a Huawei P20 with same results.  APP is deployed in Production mode.

Is it because of Battery Optimization that my FGService is killed?  I have tried to disable it globally on the phone, to no effect.

I would appreciate your assistance - seems I'm very close (as the FGService is running on the Pushy/Cordova plugin), but I just need to make sure it's not killed upon exit.

Thank you everyone, and thank you Pushy for an excellent product.  I'm deploying in China, so it's a great alternative to Firebase.

Hugs and squeezes to anyone solving this issue!

**Comment by thetongyi** [comment]
I see that not everything got parsed well when adding this topic:  

Let me try to fix this:

Hello everyone,

I have managed to update the pushy/cordova plugin to be able to support a FGService that should serve notifications, even when the APP has been closed.

To do this, I updated the JAVA files to target version 113 of the SDK.

Changes:

***************

"Plugin.xml: <framework src="me.pushy:sdk:1.0.113" />"

Pushy.js:
    {
        name: 'toggleForegroundService',
        noError: true,
        noCallback: true,
        platforms: ['android']
    },

***************

Plugin.xml

"<string name="pushy_foreground_service_title">Pushy</string>"
"<string name="pushy_foreground_service_connected">Connected to the notification service</string>"
"<string name="pushy_foreground_service_connecting">Connecting...</string>"
"<string name="pushy_foreground_service_disconnected">Not connected to the notification service</string>"

***************

PushyPlugin.java:
                if (action.equals("toggleForegroundService")) {
                    toggleForegroundService(args, callbackContext);
                }

&

        private void toggleForegroundService(JSONArray args, CallbackContext callback) {
        try {
            // Enable or disable  toggleForegroundService support
            Pushy.toggleForegroundService(args.getBoolean(0), cordova.getActivity());

            // Resolve the callback with success
            callback.success();
        }
        catch (Exception exc) {
            // Reject the callback with the exception
            callback.error(exc.getMessage());
        }
    }

***************

All works as expected, however the FGService is killed once the APP is closed.  The status bar for the FGService shows up, and shows 'Connected' etc. 

I would expect this service to stay alive / or getting restarted.  What am I missing?

I have added: 

"<service android:name="me.pushy.sdk.services.PushySocketService" android:foregroundServiceType="remoteMessaging" android:stopWithTask="false"  />"

and 

"<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />"
"<uses-permission android:name="android.permission.FOREGROUND_SERVICE_REMOTE_MESSAGING" />"

...to the "plugin.xml", but my Android phone still kills the process when exiting the APP.

I am using a Huawei Pura Ultra 70, and a Huawei P20 with same results.  APP is deployed in Production mode.

Is it because of Battery Optimization that my FGService is killed?  I have tried to disable it globally on the phone, to no effect.

I would appreciate your assistance - seems I'm very close (as the FGService is running on the Pushy/Cordova plugin), but I just need to make sure it's not killed upon exit.

Thank you everyone, and thank you Pushy for an excellent product.  I'm deploying in China, so it's a great alternative to Firebase.

Hugs and squeezes to anyone solving this issue!

**Comment by thetongyi** [comment]
[issue.txt](https://github.com/user-attachments/files/16929346/issue.txt)

I see not everything got parsed correctly, so I'm adding the full issue text as a text file to clarify.  Some HTML stripping is appearing above.

**Comment by thetongyi** [comment]
Thanks everyone.

**Comment by pushy** [comment]
Hi @thetongyi,
Thanks for reaching out, and for your kind words regarding our product. We'd be glad to assist!

Please note that we have already [added foreground service support](https://github.com/pushy/pushy-cordova/commit/4adf128c7edaa9c0e82ec1a43dc2559cc6e7d678) to the SDK yesterday in version `1.0.58` and sent you an e-mail regarding the same. Nonetheless, you have implemented well and you can keep using your own implementation if you prefer.

As per why the foreground service gets terminated when your app is killed on Huawei - this is caused due to Huawei's aggressive power optimizations which kill the app when it goes to background. Unfortunately, even foreground services are affected.

To work around it, you will need to follow the steps mentioned here to enable App Launch for your app:
https://dontkillmyapp.com/huawei

Please give it a try, and let us know if you face any issues.
