### ISSUE TITLE
Pushy blocks IONIC app when connected to wifi, but no internet access

### ISSUE THREAD

**Issue by SmetLeander** [pushy-me/pushy-cordova#5]
Hello,

I was debugging my IONIC app, and I noticed that the pushy plugin is blocking the app when there is a network connection, but there's no internet access.
there's an exception like this:
Connect exception: me.pushy.sdk.util.exceptions.PushyNetworkException: class java.net.UnknownHostException
Reconnecting in 4000ms.

Is there a workaround?

Thanks in advance!

Kind regards

**Comment by pushy** [comment]
Hi @SmetLeander,
Thanks for reporting this issue. We are unable to reproduce this behavior, but have reached out to you via e-mail to continue investigation, as it appears to be an isolated incident.

Looking forward to your e-mail response.
