### ISSUE TITLE
Android Issue: Notifications are being override in the notification panel

### ISSUE THREAD

**Issue by charmy93** [pushy-me/pushy-cordova#7]
Hello, I am using this plugin and i found that when i send multiple notification, the previous notification is being overridden by the new notification for android in the notification panel.  Is there a way where notification are being displayed in order of sending it and they don't override.

**Comment by pushy** [comment]
Hi @charmy93,
This behavior can be customized by modifying the `PushReceiver.java` file in our `pushy-cordova-receiver` plugin and randomizing the notification ID.

Edit the `PushReceiver.java` file in the following path:
```
plugins/pushy-cordova/receiver/src/android/PushReceiver.java
```

> **Note:** Do not accidentally modify `plugins/pushy-cordova-receiver/src/android/PushReceiver.java` or `platforms/android/src/me/pushy/sdk/cordova/PushReceiver.java` as your modifications will be lost when you reinstall the plugin.

Find: 

```
notificationManager.notify(1, builder.build());
```

Replace with:

```
notificationManager.notify(new Random().nextInt(10000), builder.build());
```

When you are done modifying the `PushReceiver.java` implementation, reinstall the plugin locally for changes to take effect by running the following commands in your root project directory:

```
cordova plugin rm pushy-cordova-receiver
cordova plugin add ./plugins/pushy-cordova/receiver/
```

Then, rebuild and redeploy your project and the changes will take effect.
