### ISSUE TITLE
ionic3.2 ios Pushy.register not working

### ISSUE THREAD

**Issue by JeongSeho** [pushy-me/pushy-cordova#8]
THREAD WARNING: ['PushyPlugin'] took '177.162598' ms. Plugin should use a background thread.

Unexpected call to didRegisterForRemoteNotificationsWithDeviceToken, ignoring: <5605f2e0 c11a9dcd 7bb25556 4ab86b71 794fdfe1 e2a35b1a a340a70f 55f6e557>

**Comment by pushy** [comment]
Hi @JeongSeho,
We've made contact with you via e-mail to continue investigation of the issue you are facing.
