### ISSUE TITLE
notification tap event

### ISSUE THREAD

**Issue by cainrus** [pushy-me/pushy-cordova#9]
It's impossible right now to detect notification click/tap event.

**Comment by pushy** [comment]
**Update:** Please see [this answer](https://github.com/pushy-me/pushy-cordova/issues/9#issuecomment-557316190) first.

Hi @cainrus,
For handling the click event for the notification, to open a custom activity or window, or for tracking purposes, this will require you to change the implementation of the native push notification `BroadcastReceiver`.

Modify the `PushReceiver.java` file in the following path:
```
plugins/pushy-cordova/receiver/src/android/PushReceiver.java
```

> Note: Do not accidentally modify `plugins/pushy-cordova-receiver/src/android/PushReceiver.java` or `platforms/android/src/me/pushy/sdk/cordova/PushReceiver.java` as your modifications will be lost when you reinstall the plugin.

Specifically, modify the following lines:
https://github.com/pushy-me/pushy-cordova/blob/54af4ccd7e961d3402914505d1b8f8cc1c333026/receiver/src/android/PushReceiver.java#L86-L92

You would need to add `Extras` to the Intent to track notification click:

```
launchIntent.putExtra("notificationClicked", true);
```

When you are done modifying the `PushReceiver.java` implementation, reinstall the plugin locally for changes to take effect by running the following commands in your root project directory:

```
cordova plugin rm pushy-cordova-receiver
cordova plugin add ./plugins/pushy-cordova/receiver/
```

Then, to fetch the `notificationClicked` extra from Cordova, you need to use another plugin like `cordova-plugin-intent`:
https://github.com/napolitano/cordova-plugin-intent

```
  //To get the intent and extras when the app it's open for the first time
    window.plugins.intent.getCordovaIntent (function (intent) {
        intenthandler(intent);
    });

    //To get the intent and extras if the app is running in the background
    window.plugins.intent.setNewIntentHandler (function (intent) {
        intenthandler(intent);
    });

    //To handle the params
    var intenthandler = function (intent) {
          if (intent && intent.extras && intent.extras.notificationClicked) {
        //Do something
          }
    };
```

**Comment by pushy** [comment]
Hi @cainrus,
Great news! We have just finished integrating this functionality into the SDK.

Call the `Pushy.setNotificationClickListener((data) => {})` method from your application to listen for when the user clicks your notifications:

```
// Listen for push notifications clicked
Pushy.setNotificationClickListener(function (data) {
    // Print notification payload data
    console.log('Clicked notification: ' + JSON.stringify(data));

    // Display an alert with the "message" payload value
    alert('Clicked notification: ' + data.message);

    // Navigate the user to another page or 
    // execute other logic on notification click
});
```

This method is supported on both Android and iOS. Inside this method, you can then check the notification payload which was clicked and direct the user to the relevant page in your Cordova app or execute other custom logic on notification click.

To be able to access this method, please update the Pushy Cordova SDK in your app by running the following commands in the root of your Cordova project (these will delete any modifications you have made to `pushy-push-receiver`):

```
cordova plugin remove pushy-cordova-receiver
cordova plugin remove pushy-cordova

cordova plugin add pushy-cordova@1.0.29
cordova plugin add ./plugins/pushy-cordova/receiver/
```

Please let me know if you face any issues.
